### ISSUE TITLE
[LwM2M] Updates

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#131]
- [  ] Tidy up LwM2M / Get Involve column
  - [x] Add a new microcard `Newsletter`  / Apply
- [x] Remove folder and files which content will be provided from OMASPECWORKS
  - [x] The column with microcards stays but the files are deleted.
- [x] Overall check of LwM2M page

**Comment by gocadimic** [comment]
@jpradocueva, Those are different from where the issue was created; it's unclear what should be updated now.
