### ISSUE TITLE
[Polcies-Terms] Content

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#151]
We need to update the following pages under `/omaspecworks/about/policies-terms/`:
- [x] `use-agreement` Bring content from https://omaspecworks.org/about/policies-and-terms-of-use/use-agreement/
- [x] `trademarks`https://omaspecworks.org/about/policies-and-terms-of-use/trademarks-and-affiliate-logos/
- [x]  `openness` Bring content from https://omaspecworks.org/about/policies-and-terms-of-use/openness-policy/ 
> Note Ensure all the links are working inside of this new content.

**Comment by gocadimic** [comment]
Resolved in [PR #194 ](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/194)

**Comment by gocadimic** [comment]
After merging `policies-terms-pages`, I am closing this issue.
