### ISSUE TITLE
[Membership] Content

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#152]
Update the following content:
### Membership
- [x] `join` --> Link to "Membership Enquiries" (contact us)
- [x] `Newsletter` --> Add HubSpot (existing webform script)

**Comment by jpradocueva** [comment]
@gocadimic, we should add a link to the "Newsletter" on the following membership page: (local url) http://localhost:3000/omaspecworks/membership/
- [ ] Add a link to "Newsletter"
- [ ] Add the content as bullet points for "Newsletter" and "Join OMA" rather than inline text as it is now.

**Comment by gocadimic** [comment]
Resolved in PR #235.
