### ISSUE TITLE
[PUblic Documents]

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#156]
@gocadimic there is a problem with the URLs under the White Papers section of https://technical.openmobilealliance.org/public_documents.html. The name of some document have been added to a previous file name but there is no link provided.
Please review the content and update the new website on http://localhost:3000/specifications/search/public-docs

**Comment by gocadimic** [comment]
Resolved in PR #171

**Comment by jpradocueva** [comment]
@gocadimic  There is still another issue. There are two documents in the same line. 
The problem is that the document OMA-LwM2M-Ready-for-5G is not in the FT, it was uploaded to the omaspecwebsite. 
1. You need to download the document from here and upload it to the FTP/whitepapers
2. Add the entry on the table as a new document
See image:
![image](https://github.com/user-attachments/assets/3ebbebfc-a6cd-4c9d-adfb-d8984e458a9b)

**Comment by gocadimic** [comment]
resolved in PR #187 and PR #186
