### ISSUE TITLE
[Get Contact] create page & link to that page

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#158]
- [x]  We need to resolve `Contact Us`. Where is the page that can be reached from the icon on the top right-hand side?
- [x] Every menu has `Contact Us`, we need to link it directly to that common page

Possible content to add to the "Contact Us" page:

> How to Contact Us
If you have any questions or require further information about OMA protocols, please feel free to reach out to us. Our team of experts is available to provide guidance and answer any inquiries you may have.
General Inquiries: For general questions about OMA, its protocols, or its initiatives, you can contact us via email at [helpdesk@omaorg.org](mailto:helpdesk@omaorg.org).
Technical Support: If you require technical assistance with OMA standards or need clarification on specific protocol implementations, please reach out to our technical team at [helpdesk@omaorg.org](mailto:helpdesk@omaorg.org).
Membership Inquiries: Interested in becoming a member of OMA? Membership offers numerous benefits, including access to the latest OMA specifications, participation in working groups, and the ability to influence the future direction of mobile standards. To learn more about membership options and benefits, or to start the application process, contact us at [membership@omaorg.org](mailto:membership@omaorg.org).

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/164) connected to this issue

**Comment by jpradocueva** [comment]
@gocadimic, now you can create the PRs to address the above requirements. Thanks
