### ISSUE TITLE
[API Inventory] re do the pages

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#167]
The original content is in https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/blob/master/API_Inventory.html
- [ ] re do the pages for API intentory (specifications/api/...)

**Comment by gocadimic** [comment]
Resolved in PR #173 .

**Comment by gocadimic** [comment]
Closed as resolved and merged.
