### ISSUE TITLE
[Enabler Registries] Add links and content

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#202]
### Enabler Registries page
* Link on the old website: https://technical.openmobilealliance.org/registries.html and
* Link: https://technical.openmobilealliance.org/OMNA/registerpage.html#wsp-content-type-codes (by clicking in register)
* Link to the new website: https://temp.openmobilealliance.org/specifications/registries/enablers
### Problem:
- [x]  Add links to the table
- [x] Add page available via `Register` link
- [x] Add text sections about the table.

![image](https://github.com/user-attachments/assets/6083ad4f-0f17-40b1-b673-b4ad6f036c37)

**Comment by gocadimic** [comment]
Refer to PR #227.
