### ISSUE TITLE
[LwM2M Objects] Move Object ID table to the top of the Objects table

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#204]
### Move ObjectsID table to registry table
* Old website: https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html
See image
![image](https://github.com/user-attachments/assets/0ff17ee5-8dcd-4079-b90e-e67edbb99697)

* New website: https://temp.openmobilealliance.org/lwm2m/resources/registry/resources
* Move `ObjectID Classes table` from https://temp.openmobilealliance.org/lwm2m/resources/registry

**Comment by gocadimic** [comment]
Resolved in PR #215

**Comment by jpradocueva** [comment]
@gocadimic the ObjectID Classes table (Local link: http://localhost:3000/lwm2m/resources/registry) needs to be at the top of the LwM2M Registry page, here (local link: http://localhost:3000/lwm2m/resources/registry/objects)

**Comment by gocadimic** [comment]
@jpradocueva, ObjectsID classes table moved to the registry/objects page.

**Comment by gocadimic** [comment]
@jpradocueva, the ObjectsID classes table has been moved to the registry/objects page.

**Comment by jpradocueva** [comment]
@gocadimic Thanks!
