### ISSUE TITLE
[Dynamic Table] Pending Features

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#211]
### Functionality to add:
- [x] `Show X` [25, 50, 100, ALL]. In alignment with the Search function that it is shorter.
- [x] `Export`
- [x] `Showing x to x of Y entries`

See image:

![image](https://github.com/user-attachments/assets/fee8db4b-4e74-41dd-b40b-de16a4602f8d)

**Comment by jpradocueva** [comment]
### Ability to display/hide and order properties in the filter-box and table.
* The order in the markdown document forces the order in the filter box. This is a limitation.
- [ ] Add a new field that sets the order of active properties in the filter box, e.g., `filterOrder` for each property. 
- [ ] Add a new field to hide the property in the table. 

#### Example:
Local website: http://localhost:3000/specifications/search/specifications
Old website: https://technical.openmobilealliance.org/index.html
* In the table, hide, Enabler name
![image](https://github.com/user-attachments/assets/9d83066b-4622-455c-bace-1e0ca26fa904)

**Comment by jpradocueva** [comment]
- [ ]  The information in the filter box should be organized by default in ascending alphabetic order.

![image](https://github.com/user-attachments/assets/c6219d1f-8274-447e-b591-703f142cba67)

**Comment by jpradocueva** [comment]
- [ ] Ability to have a different order of appearance between the filter box and the table.  See an example in the LwM2M Resources Dynamic Table:
![image](https://github.com/user-attachments/assets/f5514110-77a0-47ad-9299-b302dd7bac67)

**Comment by rubystream** [comment]
The remaining items are addressed in PR #246

**Comment by jpradocueva** [comment]
All completed. It works beautifully!!
