### ISSUE TITLE
[DT: Specifications] Enhancements

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#212]
* Local path: http://localhost:3000/specifications/search/specifications
#### Filter Box
- [x] `Year`. Add Year (only). Similarly, as on the [old specifications page](https://technical.openmobilealliance.org/index.html). 
* Year field should be placed between `Status` and `Doc Type`

### Table
- [x] `File Name` should be listed as a first column
- [x] Hide the following columns 'Name`, `Version`, `date`

We are seeking a similar view as:
![image](https://github.com/user-attachments/assets/63209dd4-c980-4795-b6c6-c3f0ac9d1620)

**Comment by rubystream** [comment]
Addressed in PR #221

**Comment by jpradocueva** [comment]
@rubystream this looks good! I am merging it now. I see there is a writing instruction that it shouldn't be there but we can delete it a late stage.
![image](https://github.com/user-attachments/assets/232c4bf9-d84d-4bbd-bbea-e3431f123248)

**Comment by rubystream** [comment]
PR #223 address this issue
