### ISSUE TITLE
[DT: LwM2M Objects] Enhancements

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#214]
### Enhancements to LwM2M Objects dynamic table:
* Transform a JSON value, e.g. source = 0 into a string "OMA Objects"

#### Filter Box
- [x] Add "Source" property to the first column but convert the number into:
* "0": OMa Labels
* "1": Standards Organizations Labels
* "2": Companies or individuals

#### Table
- [x]  The "LwM2M Editor" field is not uploading the object into the LwM2M Editor Tool
- [x]  Replace the URL specifications with an icon to download the spec

**Comment by rubystream** [comment]
PR #218 address all reported topics

**Comment by jpradocueva** [comment]
@we need to figure out how to hide the "Source" column from the table.

**Comment by jpradocueva** [comment]
- [ ] Hide `Source` and remove "useFetch". See image below:
![image](https://github.com/user-attachments/assets/21d07754-929d-44af-a47f-0200af902fe7)

**Comment by jpradocueva** [comment]
Address by #223
