### ISSUE TITLE
[DT: LwM2M Resources] Issues

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#215]
This table has some minor issues to resolve.

### Filter Box
- [x]  Add "Submitter" property as first column.
- [x]  Remove the link from the "Name" property. Some names display an anchor in HTML. See below

![image](https://github.com/user-attachments/assets/8529d67b-8905-443d-825b-20c75df798b6)

**Comment by rubystream** [comment]
The PR #217 address this issues.

**Comment by rubystream** [comment]
The links in the rows is based on https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html 

![Screenshot from 2024-09-29 09-49-47](https://github.com/user-attachments/assets/52c942d8-1eb9-48c5-8780-94c409c2fd51)

**Comment by jpradocueva** [comment]
@rubystream ok, I see it is embedded in the Common.xml file. I forgot about it! I am closing the issue. Thanks
