### ISSUE TITLE
[OMNA Registries] Add links to registries and to Register

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#222]
The landing page of OMNA Enabler Registries: (local url) http://localhost:3000/specifications/registries/enablers
Content: (local content) --> public/omna  It contains all the HTML files in the old [OMNA Registry page](https://technical.openmobilealliance.org/registries.html)

- [x] Add a link to view and to the register page for each registry
- [x]  Add the following content to the OMNA Registries landing page (local url: http://localhost:3000/specifications/registries). Each `Register` is linked to a subsection of this page.

**Comment by jpradocueva** [comment]
@gocadimic, @FroudeDescartes Dejan will create the architecture for these pages.

**Comment by rubystream** [comment]
This issues is addressed in PR #237
