### ISSUE TITLE
Issues related to deployment behind the www.openmobilealliance.org reverse proxy

### ISSUE THREAD

**Issue by Evadon-Nathan** [OpenMobileAlliance/oma-knowledge-base#229]
I have done a test of running the gh-pages behind the reverse proxy of www.openmobilealliance.org and I have run into some issues. So I am opening this issue to keep track of them.

The test deployment is here:
[devwww.openmobilealliance.org](devwww.openmobilealliance.org)

Or a clean reverse proxy (with no files, directory browsing from the existing openmobilealliance.org site)
[devtest.openmobilealliance.org](devtest.openmobilealliance.org)

(Note: this DEV environmnent is not turned on all the time as it is set to automatically shut down at a specific time each day to save expenses. So if anyone working on this needs it to be up 24/7, let me know and I'll stop the auto-shutdowns of the environment for the duration)

- Nuxt appears to need to use the /api/... path to work. There is an existing folder for an api service at www.openmobilealliance.org/api/... So there is a clash here. Either Nuxt needs to be adjusted to have a different path used than /api/ or the /api/ path on www.openmobilealliance.org/api/ needs to change. Alternatively, finding out what the specific path pattern that Nuxt uses under the /api/ path so I can create a rule to make sure it gets proxied, while leaving the original openmobilealliance.org/api service to also work (hopefully, as long as there aren't more path clashes). 
- When hitting refresh in the browser, it changes the URL to the reverse proxy address. I'm not familiar enough with Nuxt to know why this might happen. I am running the gh-pages behind an IIS reverse proxy. I can test this behind an NGINX server reverse proxy to see if it still does the same. But I suspect this is a Nuxt issue or setting that is needed to allow it to run behind a reverse proxy.
- Images are way too big

**Comment by jpradocueva** [comment]
https://nuxt.com/docs/getting-started/deployment

**Comment by rubystream** [comment]
the `api` folder issue is addressed in PR  #275

**Comment by Evadon-Nathan** [comment]
I have found and fixed the issue with IIS reverse proxying to gh-pages. It was a setting called "reverse rewrite host in response headers" that needed turning on.

So no need to clone the repo locally and changes to gh-pages will now happen as quickly as GitHub processes them as it's being served directly from them.

You can find the changes working at devwww.openmobilealliance.org (while the environment is turned on. It turns off automatically at 8pm UTC).

I will close this issue now and open a new one just to track the image file size issue separately.
