### ISSUE TITLE
[Landing Page] Add Floating Micro-cards 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#231]
- [x]  Add floating microcards to the landing page with two micro-cards:
* Open SVE-42 Registration
* Open Members meeting registration

**Comment by FroudeDescartes** [comment]
Add either carousel or two microcards as a floating element on our landing page, at the right side

**Comment by FroudeDescartes** [comment]
Addressed in this [PR#253](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/253)

**Comment by jpradocueva** [comment]
@FroudeDescartes We should consider creating a new floating micro-card constructor. In this way it is easy to apply changes to different content.
