### ISSUE TITLE
[Validate website content] 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#234]
Check the old websites:
- [x] OMASpecworks
- [x] Technical Pages *: https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html
- [x] LwM2M Pages *: https://lwm2m.openmobilealliance.org/
- [x] Guidelines: https://guidelines.openmobilealliance.org/
- [x] Tools: https://wiki-archive.openmobilealliance.org/Tools/index.html
- [x] Working Groups: https://openmobilealliance.github.io/oma_working_groups/

**Comment by gocadimic** [comment]
Closed for now
