### ISSUE TITLE
[Policies and Terms - question] Missing link to corespodent document

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#250]
Question:

The Release Program document in http://localhost:3000/omaspecworks/about/policies-terms/openness goes to the Technical pages: http://www.openmobilealliance.org/Technical/releaseprogram.aspx.

It's not clear if the path is correct.

**Comment by jpradocueva** [comment]
@gocadimic, we cannot have any link pointing to the old technical pages. We need to find the equivalent page on the new website where to point to.

**Comment by jpradocueva** [comment]
@gocadimic please see PR #269 and update this ticket if you see any other problems.
