### ISSUE TITLE
[OMA and LwM2M Logos] Incorrect type

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#251]
https://temp.openmobilealliance.org/oma-events/test-events

**Comment by FroudeDescartes** [comment]
This is addressed in [PR#252](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/252), but check it out for dark mode incompatibility.

**Comment by jpradocueva** [comment]
Problem solved.
