### ISSUE TITLE
[Link Problem] Members' Meeting

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#254]
- [ ] The link [REGISTER HERE] is not working. It is not different in color and is not easy to identify. I believe the problem is that it is inside a table with some special CSS.
* http://localhost:3000/oma-events/members-meetings

**Comment by FroudeDescartes** [comment]
[PR#255](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/255) connected to this issue
