### ISSUE TITLE
[OMASPECWORKS/Policies & Terms] Missing document

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#256]
The [Release Program](http://www.openmobilealliance.org/Technical/releaseprogram.aspx) on the [Openness Policy page](https://temp.openmobilealliance.org/omaspecworks/about/policies-terms/openness) is not correct, and it's not clear where the source document can be found.

**Comment by jpradocueva** [comment]
@gocadimic, please review and merge PR #269

**Comment by jpradocueva** [comment]
I have added further changes to PR #269. By the way, the issue is NOT `265` but. `256`

**Comment by gocadimic** [comment]
We can close this issue.
