### ISSUE TITLE
[Join-Us] Additional content?

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#258]
We can consider adding a new section or page on OMA Governance; see https://openmobilealliance.github.io/oma_working_groups/process-governance.

- OMA Process
  -  Governance

**Comment by jpradocueva** [comment]
@gocadimic, the plan is to bring the content to the [OMA Working Groups](https://openmobilealliance.github.io/oma_working_groups/) website once the signing into the website is available. Most of the content in these pages is private and should be available only to OMA Members.
