### ISSUE TITLE
[Events] Update

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#272]
@gocadimic, please review and merge (if you agree) the changes in the PR #273

**Comment by jpradocueva** [comment]
- [ ] @FroudeDescartes, the script for this button looks different. See below:
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/338f8c61-7ff3-43cf-8e4a-0a60f044e13b">
- [ ] Also, I have noticed these errors:
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/0e76ec36-9e5a-4c45-8143-dfedb3bb4895">

**Comment by jpradocueva** [comment]
@FroudeDescartes, 
- [ ] Icon in Test Events table is not aligned with the rest of the row content.
![image](https://github.com/user-attachments/assets/5342cefd-8d0a-41a7-837c-20186b3a9599)

**Comment by FroudeDescartes** [comment]
> * [ ]  @FroudeDescartes, the script for this button looks different. See below:
> 
> <img alt="image" width="1494" src="https://private-user-images.githubusercontent.com/3258579/375919298-338f8c61-7ff3-43cf-8e4a-0a60f044e13b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NzA5ODksIm5iZiI6MTcyODc3MDY4OSwicGF0aCI6Ii8zMjU4NTc5LzM3NTkxOTI5OC0zMzhmOGM2MS03ZmYzLTQzY2YtOGU0YS0wYTYwZjA0NGUxM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMjIwNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM0ZWMwZWE3NmQzZGViY2U0MzI1Zjg4MmU4NjUxYmUwYjYzZTY5NzU5MTVjNThiY2U3YmUxZjdlOWU3NTM3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fKGoDF7Y3j1sYLnopONaY85rDnUvo0LXB7jJqye7Coc"> - [ ] Also, I have noticed these errors: <img alt="image" width="1421" src="https://private-user-images.githubusercontent.com/3258579/375919378-0e76ec36-9e5a-4c45-8143-dfedb3bb4895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NzA5ODksIm5iZiI6MTcyODc3MDY4OSwicGF0aCI6Ii8zMjU4NTc5LzM3NTkxOTM3OC0wZTc2ZWMzNi05ZTVhLTRjNDUtODE0My1kZmVkYjNiYjQ4OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMjIwNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMxMTRlYzIzNmJhYmZiNGI3YTVjZmQ5MDI3NDIwYWMyNDI2YzMwYjVmMDFkZmQzODcyY2YxYzZjMmVkNjg2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GyN0yx6XxQbPL7_AzSgOgMt-LhsDjNybAah1yFypMqc">

Lets leave a reply for this for our upcoming meeting because it would be too long to explain it here. But you are right, it is different and I will see to change it to the one we used to

**Comment by FroudeDescartes** [comment]
Resolved in [PR#279](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/279)
