### ISSUE TITLE
[Missing Guest Policy] 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#282]
This is the content that we need to bring into the new website.
https://technical.openmobilealliance.org/guest.shtml

Probably, it should go under "Policies & Terms" folder, https://temp.openmobilealliance.org/omaspecworks/about/policies-terms

**Comment by gocadimic** [comment]
Addressed in PR #286

**Comment by jpradocueva** [comment]
@gocadimic, feel free to close issues if you believe that they are fully resolved by the PR.
