### ISSUE TITLE
[Landing Pag] Move the Menu to the top

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#325]
- [ ] Feedback from members. They want the menu on the landing page move to the top and move the event announcements where the menu is.

![image](https://github.com/user-attachments/assets/fced0fc7-c9b3-4e75-8ac8-19c6b0a14a8c)

![image](https://github.com/user-attachments/assets/dc137e2c-f591-495c-9675-147376de4c7a)

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/336) connected to this issue
