### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID - only for dev team] slug.vue file

### ISSUE THREAD

**Issue by FroudeDescartes** [OpenMobileAlliance/oma-knowledge-base#352]
- [x] Header is way too big, needs to be smaller height
- [x] Footer height is also too big- make it smaller
- [x] Potentially set the logo to be without text
- [x] prevNextPage button are not rendered correctly, overlapping text and no space between them
- [x] add `mb` to the prevNextPage
- [x] login container is way too transparent- add some blur to it

**Comment by jpradocueva** [comment]
@FroudeDescartes what link are you referring to?

**Comment by FroudeDescartes** [comment]
@jpradocueva this is not for specific link, rather a needed changes that I have observed during the testing of links from Sitemap. Mainly, changes are to be found in [...slug].vue file which suggests that things to change are appearing on every page except landing page.

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/367) connected to this issue
