### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] https://openmobilealliance.org/oma-events/test-events

### ISSUE THREAD

**Issue by FroudeDescartes** [OpenMobileAlliance/oma-knowledge-base#354]
- [ ] Image spills over the boundry
![Screenshot_20241105-150510](https://github.com/user-attachments/assets/dc898120-558d-46f1-bd62-9d4bea84404b)

**Comment by jpradocueva** [comment]
- [ ] It is displayed correctly on the iPhone.

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/440) resolving this issue but POSTPONED inscription could not be now so prominent
