### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Title breakout outside of the cardbox

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#356]
**URL:** https://openmobilealliance.org/
     **Device Type:** Android v14
     **Issue Description:** When scrolling the cardboxes, most titles pop out outside the size of it.
     **Steps to Reproduce:**
       1. Open the URL on Android v14.
       2. Scroll over the page
       3. Review content display
     **Screenshots:** ![WhatsApp Image 2024-11-05 at 10 36 04](https://github.com/user-attachments/assets/3a52c522-1563-4d8d-a770-cd3813f0eb09)
![WhatsApp Image 2024-11-05 at 10 44 20](https://github.com/user-attachments/assets/80693fdf-d57a-4025-97ed-88306b784a61)

**Comment by gocadimic** [comment]
This issue is related to Issue #351

**Comment by jpradocueva** [comment]
- [ ] displays correctly on the iPhone.
![image](https://github.com/user-attachments/assets/8ebca9b5-e709-4d15-9f7b-cb6e71e7c175)

**Comment by FroudeDescartes** [comment]
This issue should be resolved with connected issue named above
