### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Insufficiently visible text

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#357]
**URL:** https://openmobilealliance.org/announcement
     **Device Type:** Android v14
     **Issue Description:** Poorly visible text in a light mode
     **Steps to Reproduce:**
       1. Open the URL on Android v14.
       2. Scroll over the page
       3. Review content display

     **Screenshots:** 
![WhatsApp Image 2024-11-05 at 16 40 51](https://github.com/user-attachments/assets/896432a6-d60c-4fe3-b896-7aa7c9c7a05d)

**Comment by jpradocueva** [comment]
- [ ]. Same problem as seen on the desktop and iPhone.

**Comment by FroudeDescartes** [comment]
I think this page is irrelevant because it won`t be accessible by users. It is just to populate with text that will be presented in `ShAnnouncement`.
