### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Overlapping Previous and Next page's titles

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#358]
URL:** https://openmobilealliance.org/contact-us
     **Device Type:** Android v14
     **Issue Description:** At the end of the page, the previous and next pages are overlapping
     **Steps to Reproduce:**
       1. Open the URL on Android v14.
       2. Scroll over the page
       3. Review the end of the page where the previous and next pages are presented
       4. Actual: The titles of the previous and next page are partially overlapped.
     **Screenshots:** 
![Screenshot_20241105_165011_Chrome](https://github.com/user-attachments/assets/0cc78651-163d-4385-86cd-a5ead7389c1d)

**Comment by gocadimic** [comment]
This issue is related to Issue #351

**Comment by jpradocueva** [comment]
- [ ]  Same problem when rendering in an iPhone

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/365) resolving this issue
