### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Broken links at SyncML

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#366]
URL:** https://openmobilealliance.org/omaspecworks/collaborate/affiliates/wap-forum
     **Device Type:** Android v14
     **Issue Description:**The following links are broken/not landed correctly:

- [x] Public Available Documents
- [x] Click here to view Use Agreement
- [x] SyncML Specification version 1.0.1 (Zip)
- [x] SyncML White Papers
- [x] SyncML Presentations
- [x] SyncML Specification version 1.0.1 (Zip)
- [x] SyncML Meta Information Version 1.0.1 - DTD
- [x] SyncML Device Information Version 1.0.1 - DTD
- [x] SyncML White Paper (html)

   **Steps to Reproduce:**

       1. Open the URL on Android v14.
       2. Scroll over the page
       3. Click to open links above
       4. Actual: The link seems to present 404 or not landing correctly

**Comment by jpradocueva** [comment]
Public Available Docs: https://openmobilealliance.org/specifications/search/public-docs#oma-public-documents
