### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] https://www.openmobilealliance.org/tools/lwm2m-api-registry

### ISSUE THREAD

**Issue by FroudeDescartes** [OpenMobileAlliance/oma-knowledge-base#369]
This link is a hit or miss. Sometimes it works, other times it doesn\`t.
![WhatsApp slika 2024-11-06 u 18 46 58_650fbfe5](https://github.com/user-attachments/assets/9e45182e-c680-49ae-8182-9dbdc19382ad)

Can you guys check and see if you can replicate Error?
Also, it could happen that it renders the page but table is empty

**Comment by gocadimic** [comment]
It acts strangely. For the moment, it responds as 404, and then it loads correctly. It might be a redirecting issue.
All the content is there, including the table.

**Comment by gocadimic** [comment]
LGTM now

**Comment by FroudeDescartes** [comment]
LGTM -> closing
