### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Overlapping microcards preview

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#384]
### URL

https://openmobilealliance.org/omaspecworks/about/ipr/non-members
https://openmobilealliance.org/omaspecworks/about/ipr/members
https://openmobilealliance.org/specifications/search/specifications
https://openmobilealliance.org/specifications/search/enablers

### Pre-Conditions

Open the URL on Android v14

### Steps to Reproduce

Scroll over the page.
- Preview OMA Non-Memebres IPR Declarations Table.
- Preview Quick Filters table section

### Expected Results

The content below 'Quick Filters' should be appropriately presented, seeing all listed items in all four columns.

### Actual Results

The content overlaps and is not fully visible on the screen, especially the column headers.

### Attachments

![Screenshot_20241111_162808_Chrome](https://github.com/user-attachments/assets/ecc61b9b-f51f-4913-a1d3-d07966927149)

### Environment - Browser

Chrome

### Environment - OS

macOs

### Severity

Medium (P2)

### Status

Triage

**Comment by FroudeDescartes** [comment]
PR #397 resolving this issue
