### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Dynamic table row is not enirely visible

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#386]
### URL

https://openmobilealliance.org/lwm2m/resources/registry/objects

### Pre-Conditions

To open the URL, use Android v14

### Steps to Reproduce

Scroll over the page.

Observe OMA LwM2M Registry (Objects) dynamic Table.
Observe the table rows, scrolling down across the table.

### Expected Results

The whole content of the table rows should be visible without the need for horizontal scrolling. The content is unevenly distributed on the page, leaving significant areas of empty white space.

### Actual Results

To see each row value, horizontal scrolling is needed. 

### Attachments

![Screenshot_20241111_210121_Chrome](https://github.com/user-attachments/assets/d85cba57-aa57-43b0-a628-1076107f752f)

### Environment - Browser

Chrome

### Environment - OS

macOs

### Severity

Low (P3)

### Status

Triage

**Comment by gocadimic** [comment]
I get the same result.

**Comment by jpradocueva** [comment]
This seems to be related to issue #426

**Comment by gocadimic** [comment]
It's fixed, closing
