### ISSUE TITLE
[Contact-US] Missing link/email for Technical comments form 

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#391]
![Untitled 2](https://github.com/user-attachments/assets/d87cf59b-2a39-4fdc-bb39-c868cc93e5ac)

**Comment by jpradocueva** [comment]
@gocadimic 
"Comments on LwM2M" --> https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues
Rest of comments should go to "helpdesk@omaorg.org"
