### ISSUE TITLE
[FTP-Documents] Upload new files

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#399]
Upload the [identified](https://docs.google.com/spreadsheets/d/14MJX5k-qSqUuCM5vgsiT-Z5kO105iLHW_kEF7Wl-ksk/edit?gid=507231729#gid=507231729) documents to the corresponding FTP folder.

**Comment by gocadimic** [comment]
Updated in [Gdocument](https://docs.google.com/spreadsheets/d/14MJX5k-qSqUuCM5vgsiT-Z5kO105iLHW_kEF7Wl-ksk/edit?gid=507231729#gid=507231729)
