### ISSUE TITLE
Changes to Resources Links

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#402]
@gocadimic 
The link to this resource, https://www.openmobilealliance.org/documents/whitepapers/LwM2M-5G,%20IoT,%20UN-SDG.pdf was changed to https://openmobilealliance.org/documents/whitepapers/LwM2M-5G-IoT-UN-SDG.pdf (without commas).

The link to this resource, https://openmobilealliance.org/documents/ipso/IPSO_Internet_Protocol_for_Smart_Objects.pdf was updated by removing the blank space before ".pdf"

Please check that these links are corrected on the new website. We shouldn't have links with blank or commas.

**Comment by gocadimic** [comment]
Resolved in PR #419
