### ISSUE TITLE
Block or Allow crawlers to access URLs to create sitemaps

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#420]
@nathan-omaorg (Issue: #407)
From the list __Resources that crawlers should not be allowed to index__ the following ones cannot be resolved with `robots.txt` but need to be addressed by the web server rooter rules:

- [ ] https://oma-knowledge-based.openmobilealliance.org/?
- [ ] https://temp.openmobilealliance.org/?

Also, we should be able to access the content in the folders listed below, but the message I am getting is "site can't be reached." The intention is to create a sitemap for the content to be indexed. Are these folders public?
From the list __Resources to expose to crawlers so they can be indexed__ the following required user authorization:
- [ ] http://www.member.openmobilealliance.org/FTP/Public_documents/?
- [ ] http://www.openmobilealliance.org/WorkProgram 
- [ ] https://www.openmobilealliance.org/WorkProgram/?

The above ones cannot be resolved using `sitemap.xml` or `robots.txt` and should be excluded from this issue.

**Comment by Evadon-Nathan** [comment]
I have opened another issue to separate these. We can continue using this issue for robot.txt and sitemap.xml issues

Here's the issue for the bad URLs
https://github.com/OpenMobileAlliance/oma-knowledge-base/issues/424

**Comment by jpradocueva** [comment]
Problem resolved in #407, #424
