### ISSUE TITLE
Unable to access these URLs for search indexing

### ISSUE THREAD

**Issue by Evadon-Nathan** [OpenMobileAlliance/oma-knowledge-base#424]
Also, we should be able to access the content in the folders listed below, but the message I am getting is "site can't be reached." The intention is to create a sitemap for the content to be indexed. Are these folders public?
From the list Resources to expose to crawlers so they can be indexed the following required user authorization:

 http://www.member.openmobilealliance.org/FTP/Public_documents/?
 http://www.openmobilealliance.org/WorkProgram
 https://www.openmobilealliance.org/WorkProgram/?

The above ones cannot be resolved using sitemap.xml or robots.txt and should be excluded from this issue.

**Comment by Evadon-Nathan** [comment]
These are all wrong URLs:
http://www.member.openmobilealliance.org/FTP/Public_documents/?
should be
https://member.openmobilealliance.org/FTP/Public_documents/
http://www.openmobilealliance.org/WorkProgram
https://www.openmobilealliance.org/WorkProgram/?

**Comment by jpradocueva** [comment]
@nathan-omaorg thanks! Your input has resolved the pending issues. There is no needed to setup a directory for https://www.openmobilealliance.org/WorkProgram 
 
@rubystream can we now create the corresponding sitemaps for?
- [ ] https://member.openmobilealliance.org/FTP/Public_documents/
- [ ] https://www.openmobilealliance.org/WorkProgram/WIDs/
