### ISSUE TITLE
[Chrome redirect] to https://openmobilealliance.org/HTTP/1.1://www.openmobilealliance.org/

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#426]
When inputting openmobilealliance.org in Chrome, the browser reconstructs the URL as https://openmobilealliance.org/HTTP/1.1://www.openmobilealliance.org/. This happened today, Thursday, Nov 28. It has been working ok until recently. 

@nathan-omaorg, do you know why this is happening? 
This problem doesn't occur in Firefox.

**Comment by FroudeDescartes** [comment]
I cannot replicate this behavior. 

### Notes

The site loads correctly

### Environment - Browser

Chrome - Version 131.0.6778.86 (Official Build) (64-bit)

### Environment - OS

Windows 11

**Comment by Evadon-Nathan** [comment]
I used the wrong server variable in the redirect from no-www to www.

It's fixed now
