### ISSUE TITLE
[Join OMA] Add DocuSign

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#436]
In the section, Join OMA; in addition, to adding the Membership Application in a PDF, we need to add a link to the DocuSign for the same document. We need to indicate that companies need to sign the DocuSign the PDF is provided for reference. 

"Joining OMA SpecWorks is a straightforward process. Complete the attached DocuSign version of the [Membership Agreement](). We also provide a PDF copy for your reference. [PDF]()"
>Note: please use the anchor instead of markdown constructors. Also, please search if there is already a DocuSign link and replace it with the new one.

**Comment by gocadimic** [comment]
Resolved in PR #439
